---
title: "Fig2 Codes"
author: "Qin He"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setvp, inclvde=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
set.seed(640)
B = 10000
n = 500

b1 = rep(0,B)
b2 = rep(0,B)

for(i in 1:B){
  xh = matrix(rnorm((n/2),0,1), nrow = n/2,ncol = 1)
  x = rbind(xh,xh)
  v = matrix(rnorm(n,0,1), nrow = n,ncol = 1)
  u = matrix(rnorm(n,0,1), nrow = n,ncol = 1)
  d = x + v
  y = d + x + u
  
  mhat = x
  overfit = (y-x)/(n**(1/2.5)) # overfit
  b1[i] = t(d - mhat)%*%(y-x-overfit)/(t(d-mhat)%*%d) # full sample
  
  # sample split of data
  splitA = matrix(c(1:(n / 2)), nrow = n / 2,ncol = 1)
  splitB = matrix(c((n / 2) + 1 :n), nrow = n/2,ncol = 1)
  
  bA = (t(v[splitA]) %*% (y[splitA] - x[splitA] - overfit[splitB] ) ) / ( (t(v[splitA])%*%d[splitA] ) )
  bB = (t(v[splitB]) %*% (y[splitB] - x[splitB] - overfit[splitA] ) ) / ( (t(v[splitB])%*%d[splitB] ) )
  
  b2[i] = (1/2)*(bA+bB) # sample splitting

}
# normalize 
b1 = (b1 - 1)/sd(b1)
b2 = (b2 - 1)/sd(b2)
edges = seq(-10,10,by = 0.05)
png("Fig2_full.png")
hist(b1,breaks = edges,freq = FALSE,main="Full Sample",xlab = "Bias")
x<-seq(-10,10,by=0.05)
curve(dnorm(x), add=TRUE,col="red")
dev.off() 
png("Fig2_split.png")
hist(b2,breaks = edges,freq = FALSE,main = "Sample Splitting",xlab = "Bias")
curve(dnorm(x), add=TRUE,col="red")
# Close the graphics device
dev.off() 
```



