---
title: "STA 640 Final"
author: "Qin He"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#rng(13867)

B = 10000;
n = 500;

# zero vectors with size B * 1 [0,0,0.....]
b1 = zeros(B,1);
b2 = zeros(B,1);

for ii = 1:B
  
    zh = randn(n/2,1);
    z = [zh;zh];
    u = randn(n,1);
    v = randn(n,1);
    x = z + u;
    y = x + z + v;
    
    mhat = z;
    overfit = (y-z)/(n^(1/3));
    
    b1(ii,1) = ((x-mhat)'*(y-z-overfit))/((x-mhat)'*x);
    
    splitA = (1:(n/2))';
    splitB = ((n/2)+1:n)';
    
    bA = (u(splitA)'*(y(splitA)-z(splitA)-overfit(splitB)))/(u(splitA)'*x(splitA));
    bB = (u(splitB)'*(y(splitB)-z(splitB)-overfit(splitA)))/(u(splitB)'*x(splitB));
    b2(ii,1) = (1/2)*(bA+bB);
end

edges = -7:.05:7;
[nb1,xb1] = histcounts((b1-1)/std(b1),edges,'Normalization','pdf');
[nb2,xb2] = histcounts((b2-1)/std(b2),edges,'Normalization','pdf');

figure;
subplot(1,2,1), bar((xb1(1:end-1)+xb1(2:end))/2,nb1,1,'FaceColor',[0,.5,.75],'FaceAlpha',.5);
hold on;
plot(edges,normpdf(edges),'r');
title('A.  Full Sample')
legend('Simulation','N(0,1)','Location','NorthWest')
subplot(1,2,2), bar((xb2(1:end-1)+xb2(2:end))/2,nb2,1,'FaceColor',[0,.5,.75],'FaceAlpha',.5);
hold on;
plot(edges,normpdf(edges),'r');
title('B.  Split Sample')
legend('Simulation','N(0,1)','Location','NorthWest')
```




```{r}
set.seed(640)
B = 10000
n = 500

b1 = rep(0,B)
b2 = rep(0,B)

for( i in 1:B){
  zh = matrix(rnorm((n/2),0,1), nrow = n/2,ncol = 1)
  z = rbind(zh,zh)
  u = matrix(rnorm(n,0,1), nrow = n,ncol = 1)
  v = matrix(rnorm(n,0,1), nrow = n,ncol = 1)
  x = z + u
  y = x + z + v
  
  mhat = z
  overfit = (y-z)/(n**(1/2.9))
  b1[i] = t(x - mhat)%*%(y-z-overfit)/(t(x-mhat)%*%x)
  splitA = matrix(c(1:(n / 2)), nrow = n / 2,ncol = 1)
  splitB = matrix(c((n / 2) + 1 :n), nrow = n/2,ncol = 1)
  
  bA = (t(u[splitA]) %*% (y[splitA] - z[splitA] - overfit[splitB] ) ) / ( (t(u[splitA])%*%x[splitA] ) )
  bB = (t(u[splitB]) %*% (y[splitB] - z[splitB] - overfit[splitA] ) ) / ( (t(u[splitB])%*%x[splitB] ) )
  
  b2[i] = (1/2)*(bA+bB)

}
# normalize 
b1 = (b1 - 1)/sd(b1)
b2 = (b2 - 1)/sd(b2)
edges = seq(-10,10,by = 0.05)
hist(b1,breaks = edges,freq = FALSE)
x<-seq(-10,10,by=0.05)
curve(dnorm(x), add=TRUE)
hist(b2,breaks = edges,freq = FALSE)
curve(dnorm(x), add=TRUE)
```



