---
title: "simulationC"
author: "TJ Tang"
date: "4/24/2022"
output: pdf_document
---

```{r setup, include=FALSE}
source("gen_data.R")
source("simulation_helper.R")
library(writexl)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
df_to_excel = function(fs,ss,name){
  df = data.frame(
    full_sample = fs,
    sample_split = ss
  )
  path = paste0(name,".csv")
  write_xlsx(df, path)
}

```


## Scenario 33-40

```{r}
ml_method = "xgboost"
n <- c(50,1000)
ncov <- c(5,100)
k <- c(2,5)
variance = 1
outcome_model = "linear"
g0_dist = "normal"
```


```{r}
count = 33 
for(a in n){
  for(b in ncov){
    for(c in k){
      ss <- fs <- c()
      for(i in 1:100){
        df <- generate_data(n=a,ncov=b,theta0=1, g0_dist = g0_dist,variance = variance,
                             outcome_model = outcome_model,seed = i)
        ss <- c(ss,sample_splitting(df,k=c,seed=640,  ml_method = ml_method))
        fs <- c(fs,full_sample(df,seed=640,  ml_method = ml_method))
        df_to_excel(fs,ss,paste(count))
      }
      count = count + 1
  }
}

}
```


## Scenario 41-48

```{r}
ml_method = "xgboost"
n <- c(50,1000)
ncov <- c(5,100)
k <- c(2,5)
variance = 1
outcome_model = "non-linear"
g0_dist = "normal"
```


```{r}
count = 41 
for(a in n){
  for(b in ncov){
    for(c in k){
      ss <- fs <- c()
      for(i in 1:100){
        df <- generate_data(n=a,ncov=b,theta0=1, g0_dist = g0_dist,variance = variance,
                             outcome_model = outcome_model,seed = i)
        ss <- c(ss,sample_splitting(df,k=c,seed=640,  ml_method = ml_method))
        fs <- c(fs,full_sample(df,seed=640,  ml_method = ml_method))
        df_to_excel(fs,ss,paste(count))
      }
      count = count + 1
  }
}

}
```


